# docker-compose.yml
version: '3.8'

services:
  wallet-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/wallet
      - SPRING_DATASOURCE_USERNAME=wallet
      - SPRING_DATASOURCE_PASSWORD=wallet123
      - TZ=America/Sao_Paulo
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: wallet123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wallet"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

