-- liquibase formatted sql

-- changeset fabiosiqueira:1757079167819-1
CREATE TABLE idempotency_key
(
    "key"          VARCHAR(100)              NOT NULL,
    user_id      VARCHAR(255)                NOT NULL,
    operation    VARCHAR(255)                NOT NULL,
    reference_id VARCHAR(255)                NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_idempotency_key PRIMARY KEY ("key")
);

-- changeset fabiosiqueira:1757079167819-2
CREATE TABLE transactions
(
    id UUID DEFAULT gen_random_uuid(),
    from_user_id  VARCHAR(255),
    to_user_id    VARCHAR(255),
    type          VARCHAR(255)   NOT NULL,
    amount        DECIMAL(19, 2) NOT NULL,
    balance_after DECIMAL(19, 2),
    description   VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);

-- changeset fabiosiqueira:1757079167819-3
CREATE TABLE wallets
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    VARCHAR(255)                            NOT NULL,
    balance    DECIMAL(19, 2)                          NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_wallets PRIMARY KEY (id)
);

-- changeset fabiosiqueira:1757079167819-4
CREATE UNIQUE INDEX uk_user_id ON wallets (user_id);

-- changeset fabiosiqueira:1757079167819-5
CREATE INDEX idx_created_at ON transactions (created_at);

-- changeset fabiosiqueira:1757079167819-6
CREATE INDEX idx_from_user_id ON transactions (from_user_id);

-- changeset fabiosiqueira:1757079167819-7
CREATE INDEX idx_to_user_id ON transactions (to_user_id);

-- changeset fabiosiqueira:1757079167819-8
CREATE INDEX idx_user_operation ON idempotency_key (user_id, operation);



